FROM debian:stretch
ADD . /
RUN apt-get update
RUN apt-get install -y curl gnupg2 apt-transport-https ca-certificates gcc
RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RUN apt-get update && apt-get install -y bazel
RUN /build.sh
